fixed `define` command
pirpyn/gdb-syntax-vscode pull request #13
Opened 2023-02-08 10:54 UTC by GitMensch

For some unknown reason I've added that wrong, there's no "command" in the define command.

Change details:
* tests:
   * renamed "document.gdb" to command".gdb
   * test.gdb: moved entries to hook.gdb / command.gdb

2023-02-08 12:37 UTC, pirpyn requested changes
I prefer to have both `define.gdb` & `document.gdb`, even if `document` use a `commandname` from `command`.
Also reading the [doc](https://sourceware.org/gdb/onlinedocs/gdb/Define.html#Define), define & define-prefix are different in what they do, so we have to separate them especially since i didn't grasp the differences between them

2023-02-08 12:37 UTC, pirpyn commented on syntaxes/gdb.tmLanguage.json
> +					"name": "meta.command.dont.gdb",
I prefer to use the full command name for "name" field, to avoid ambiguities so `meta.command.dont-repeat.gdb`

2023-02-08 12:37 UTC, pirpyn commented on syntaxes/gdb.tmLanguage.json
> +					"begin": "^[ \t]*(define(?:-prefix)?)[ \t]+([^[ \t]]+)[ \t]*$",
Approved. https://sourceware.org/gdb/onlinedocs/gdb/Define.html#index-define

2023-05-30 20:16 UTC, GitMensch commented
@pirpyn Would you mind taking this over?

2023-05-30 20:17 UTC, pirpyn commented
> @pirpyn Would you mind taking this over?

Sure, likely tomorrow

2023-05-31 07:45 UTC, merged